from pathlib import Path

path = Path("main.py")
text = path.read_text(encoding="utf-8")
old = '''            status, _ = self._git_request("DELETE", url, json_body=body)\n            if status in (200, 204):\n                self._sha_cache.pop(path, None)\n                return True\n            if status == 404:\n                self._sha_cache.pop(path, None)\n                logger.info(f"[Git Sync] 删除 {path} 时远程已不存在。")\n                return True\n            logger.error(f"[Git Sync] 删除文件失败 {path} (HTTP {status})")\n            return False\n'''
new = '''            status, _ = self._git_request("DELETE", url, json_body=body)\n            if status in (200, 204):\n                self._sha_cache.pop(path, None)\n                return True\n            if status == 404:\n                self._sha_cache.pop(path, None)\n                logger.info(f"[Git Sync] 删除 {path} 时远程已不存在。")\n                return True\n\n            if status in (409, 422):\n                self._sha_cache.pop(path, None)\n                refresh_status, refresh_data = self._git_request(\n                    "GET", url, params={"ref": branch}\n                )\n                if refresh_status == 404:\n                    logger.info(f"[Git Sync] 删除 {path} 冲突后确认远程已不存在。")\n                    return True\n                if refresh_status != 200 or not isinstance(refresh_data, dict):\n                    logger.error(\n                        f"[Git Sync] 删除 {path} 冲突后无法刷新远程 SHA "\n                        f"(HTTP {refresh_status})"\n                    )\n                    return False\n                fresh_sha = str(refresh_data.get("sha", "")).strip()\n                if not fresh_sha:\n                    logger.error(f"[Git Sync] 删除 {path} 冲突后远程响应缺少 SHA。")\n                    return False\n\n                self._sha_cache[path] = fresh_sha\n                retry_body = dict(body)\n                retry_body["sha"] = fresh_sha\n                retry_status, _ = self._git_request(\n                    "DELETE", url, json_body=retry_body\n                )\n                if retry_status in (200, 204, 404):\n                    self._sha_cache.pop(path, None)\n                    if retry_status == 404:\n                        logger.info(f"[Git Sync] 重试删除 {path} 时远程已不存在。")\n                    return True\n                logger.error(\n                    f"[Git Sync] 使用刷新 SHA 重试删除失败 {path} "\n                    f"(HTTP {retry_status})"\n                )\n                return False\n\n            logger.error(f"[Git Sync] 删除文件失败 {path} (HTTP {status})")\n            return False\n'''
if old not in text:
    raise SystemExit("target delete block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
