from pathlib import Path

path = Path("main.py")
source = path.read_text(encoding="utf-8")
old = '''    def _git_delete_file(self, path: str, message: str) -> bool:\n        \"\"\"删除远程仓库中的文件，SHA 缓存为空时会主动查询远程。\"\"\"\n        with self._git_mutation_lock:\n            sha = self._sha_cache.get(path)\n            if not sha:\n                sha = self._git_fetch_file_sha(path)\n                if not sha:\n                    logger.info(f\"[Git Sync] 跳过删除 {path}：远程文件不存在或无法获取 SHA。\")\n                    return True\n    \n            base = self._git_api_base()\n            owner = self._git_owner()\n            repo = self._git_repo()\n            branch = self._git_branch()\n            url = f\"{base}/repos/{owner}/{repo}/contents/{path}\"\n'''
new = '''    def _git_delete_file(self, path: str, message: str) -> bool:\n        \"\"\"删除远程文件；无法确认远端当前 SHA 时必须 fail-closed。\"\"\"\n        with self._git_mutation_lock:\n            base = self._git_api_base()\n            owner = self._git_owner()\n            repo = self._git_repo()\n            branch = self._git_branch()\n            url = f\"{base}/repos/{owner}/{repo}/contents/{path}\"\n\n            sha = self._sha_cache.get(path)\n            if not sha:\n                status, data = self._git_request(\n                    \"GET\", url, params={\"ref\": branch}\n                )\n                if status == 404:\n                    self._sha_cache.pop(path, None)\n                    logger.info(f\"[Git Sync] 删除 {path} 时远程已不存在。\")\n                    return True\n                if status != 200 or not isinstance(data, dict):\n                    logger.error(\n                        f\"[Git Sync] 无法确认删除目标 {path} 的远程 SHA (HTTP {status})\"\n                    )\n                    return False\n                sha = str(data.get(\"sha\", \"\")).strip()\n                if not sha:\n                    logger.error(f\"[Git Sync] 删除目标 {path} 的远程响应缺少 SHA。\")\n                    return False\n                self._sha_cache[path] = sha\n'''
if old not in source:
    raise SystemExit("target block not found")
source = source.replace(old, new, 1)
path.write_text(source, encoding="utf-8")
