from pathlib import Path


MAIN = Path("main.py")
LOST = Path("tests/test_github_ref_lost_response.py")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


main = MAIN.read_text(encoding="utf-8")

old_ref = '''    def _git_update_github_ref(self, commit_sha: str) -> bool:\n        \"\"\"将 GitHub 分支引用快进到新 commit。\"\"\"\n        base = self._git_api_base()\n        owner = self._git_owner()\n        repo = self._git_repo()\n        branch = self._git_branch()\n        url = f\"{base}/repos/{owner}/{repo}/git/refs/heads/{branch}\"\n        status, _ = self._git_request(\"PATCH\", url, json_body={\"sha\": commit_sha, \"force\": False})\n        return status == 200\n'''
new_ref = '''    def _git_update_github_ref(self, commit_sha: str) -> bool:\n        \"\"\"将 GitHub 分支引用快进到新 commit，并记录失败语义。\"\"\"\n        base = self._git_api_base()\n        owner = self._git_owner()\n        repo = self._git_repo()\n        branch = self._git_branch()\n        url = f\"{base}/repos/{owner}/{repo}/git/refs/heads/{branch}\"\n        status, _ = self._git_request(\n            \"PATCH\", url, json_body={\"sha\": commit_sha, \"force\": False}\n        )\n        if status == 200:\n            self._git_ref_update_outcome = \"success\"\n            return True\n        if status in (409, 422):\n            self._git_ref_update_outcome = \"conflict\"\n        elif status in (0,) or status >= 500:\n            self._git_ref_update_outcome = \"uncertain\"\n        else:\n            # 认证、权限、限流、分支不存在等明确拒绝都不应伪装成并发冲突。\n            self._git_ref_update_outcome = \"rejected\"\n        return False\n'''
main = replace_once(main, old_ref, new_ref, "ref updater")

old_first_failure = '''            if self._git_update_github_ref(commit_sha):\n                for git_path, _, blob_sha in items:\n                    self._sha_cache[git_path] = blob_sha\n                return True\n\n            logger.info(\"[Git Sync] GitHub ref 更新冲突，刷新 HEAD 后重试本批次。\")\n            head = self._git_get_head_commit_and_tree()\n            if not head:\n                return False\n            parent_sha, base_tree_sha = head\n\n            # PATCH 响应丢失时，分支可能已移动到本 commit，甚至又前进到它的后继。\n            # 仅当当前 tree 仍完整包含本批次全部 blob 时，才能把不确定响应收敛为成功。\n            if parent_sha == commit_sha or branch_tree_matches_items(base_tree_sha):\n                for git_path, _, blob_sha in items:\n                    self._sha_cache[git_path] = blob_sha\n                return True\n\n            retry_collision = False\n'''
new_first_failure = '''            if self._git_update_github_ref(commit_sha):\n                for git_path, _, blob_sha in items:\n                    self._sha_cache[git_path] = blob_sha\n                return True\n\n            # 真实实现每次 PATCH 都会写入 outcome；默认 conflict 仅兼容旧测试桩。\n            ref_outcome = getattr(self, \"_git_ref_update_outcome\", None) or \"conflict\"\n            if ref_outcome == \"rejected\":\n                logger.warning(\n                    \"[Git Sync] GitHub ref 更新被明确拒绝，本批次停止，不执行冲突重试。\"\n                )\n                return False\n\n            head = self._git_get_head_commit_and_tree()\n            if not head:\n                return False\n            parent_sha, base_tree_sha = head\n\n            if ref_outcome == \"uncertain\":\n                # PATCH 响应丢失时，分支可能已移动到本 commit，甚至又前进到它的后继。\n                # 仅当当前 tree 仍完整包含本批次全部 blob 时，才能把不确定响应收敛为成功。\n                if parent_sha == commit_sha or branch_tree_matches_items(base_tree_sha):\n                    for git_path, _, blob_sha in items:\n                        self._sha_cache[git_path] = blob_sha\n                    return True\n                logger.warning(\n                    \"[Git Sync] GitHub ref 更新结果不确定且无法确认已生效，本批次停止。\"\n                )\n                return False\n\n            if ref_outcome != \"conflict\":\n                logger.warning(\n                    f\"[Git Sync] GitHub ref 更新返回未知结果 {ref_outcome!r}，本批次停止。\"\n                )\n                return False\n\n            logger.info(\"[Git Sync] GitHub ref 更新冲突，刷新 HEAD 后重试本批次。\")\n            retry_collision = False\n'''
main = replace_once(main, old_first_failure, new_first_failure, "first ref failure flow")

old_retry = '''            if not self._git_update_github_ref(retry_commit_sha):\n                refreshed = self._git_get_head_commit_and_tree()\n                if not refreshed:\n                    return False\n                if (\n                    refreshed[0] != retry_commit_sha\n                    and not branch_tree_matches_items(refreshed[1])\n                ):\n                    return False\n\n            for git_path, _, blob_sha in items:\n'''
new_retry = '''            if not self._git_update_github_ref(retry_commit_sha):\n                retry_outcome = (\n                    getattr(self, \"_git_ref_update_outcome\", None) or \"conflict\"\n                )\n                if retry_outcome != \"uncertain\":\n                    return False\n                refreshed = self._git_get_head_commit_and_tree()\n                if not refreshed:\n                    return False\n                if (\n                    refreshed[0] != retry_commit_sha\n                    and not branch_tree_matches_items(refreshed[1])\n                ):\n                    return False\n\n            for git_path, _, blob_sha in items:\n'''
main = replace_once(main, old_retry, new_retry, "retry ref failure flow")

old_pending = '''        if self._git_platform() == \"github\":\n            if self._git_push_batch_github(items):\n                try:\n                    for git_path, content in items:\n                        remote_sha = self._sha_cache.get(git_path, \"\")\n                        self._remember_verified_remote_content(\n                            git_path, content, remote_sha, save=False\n                        )\n                finally:\n                    self._save_hash_index()\n                logger.info(f\"[Git Sync] 已批量提交 {len(items)} 张图片到 GitHub。\")\n                return len(items), 0, 0\n            logger.warning(\"[Git Sync] GitHub 批量提交失败，回退为逐文件推送当前批次。\")\n\n        success = 0\n'''
new_pending = '''        if self._git_platform() == \"github\":\n            self._git_ref_update_outcome = None\n            if self._git_push_batch_github(items):\n                try:\n                    for git_path, content in items:\n                        remote_sha = self._sha_cache.get(git_path, \"\")\n                        self._remember_verified_remote_content(\n                            git_path, content, remote_sha, save=False\n                        )\n                finally:\n                    self._save_hash_index()\n                logger.info(f\"[Git Sync] 已批量提交 {len(items)} 张图片到 GitHub。\")\n                return len(items), 0, 0\n            ref_outcome = getattr(self, \"_git_ref_update_outcome\", None)\n            if ref_outcome in {\"rejected\", \"uncertain\"}:\n                logger.warning(\n                    \"[Git Sync] GitHub 批量提交因 ref 更新拒绝/结果不确定而停止，\"\n                    \"不回退逐文件写入。\"\n                )\n                return 0, len(items), 0\n            logger.warning(\"[Git Sync] GitHub 批量提交失败，回退为逐文件推送当前批次。\")\n\n        success = 0\n'''
main = replace_once(main, old_pending, new_pending, "pending fallback")

MAIN.write_text(main, encoding="utf-8")

lost = LOST.read_text(encoding="utf-8")
old_helper = '''    plugin = types.SimpleNamespace(\n        _git_mutation_lock=threading.RLock(),\n        _sha_cache={},\n        _git_get_head_commit_and_tree=Mock(side_effect=heads),\n        _git_create_github_tree=Mock(side_effect=lambda base, entries: f\"built-{base}\"),\n        _git_create_github_commit=Mock(side_effect=lambda message, tree, parent: f\"commit-{parent}\"),\n        _git_update_github_ref=Mock(side_effect=update_results),\n        _git_platform=lambda: \"github\",\n        _git_api_base=lambda: \"https://api.github.test\",\n        _git_owner=lambda: \"owner\",\n        _git_repo=lambda: \"repo\",\n    )\n\n    def request(method, url, params=None, timeout=None, **kwargs):\n'''
new_helper = '''    plugin = types.SimpleNamespace(\n        _git_mutation_lock=threading.RLock(),\n        _sha_cache={},\n        _git_ref_update_outcome=None,\n        _git_get_head_commit_and_tree=Mock(side_effect=heads),\n        _git_create_github_tree=Mock(side_effect=lambda base, entries: f\"built-{base}\"),\n        _git_create_github_commit=Mock(side_effect=lambda message, tree, parent: f\"commit-{parent}\"),\n        _git_platform=lambda: \"github\",\n        _git_api_base=lambda: \"https://api.github.test\",\n        _git_owner=lambda: \"owner\",\n        _git_repo=lambda: \"repo\",\n    )\n\n    updates = iter(update_results)\n\n    def update_ref(commit_sha):\n        result = next(updates)\n        if isinstance(result, tuple):\n            ok, outcome = result\n        else:\n            ok = bool(result)\n            outcome = \"success\" if ok else \"uncertain\"\n        plugin._git_ref_update_outcome = outcome\n        return ok\n\n    plugin._git_update_github_ref = Mock(side_effect=update_ref)\n\n    def request(method, url, params=None, timeout=None, **kwargs):\n'''
lost = replace_once(lost, old_helper, new_helper, "lost response helper")
LOST.write_text(lost, encoding="utf-8")
