from pathlib import Path

path = Path("main.py")
source = path.read_text(encoding="utf-8")

old_tree_tail = '''        return result\n\n    def _ensure_perceptual_index(self) -> None:\n'''
new_tree_tail = '''        return result\n\n    def _git_list_tree_at(self, tree_sha: str) -> list[dict] | None:\n        \"\"\"Read one immutable GitHub tree snapshot by SHA for destructive operations.\"\"\"\n        if self._git_platform() != \"github\" or not str(tree_sha).strip():\n            return None\n        base = self._git_api_base()\n        owner = self._git_owner()\n        repo = self._git_repo()\n        url = f\"{base}/repos/{owner}/{repo}/git/trees/{str(tree_sha).strip()}\"\n        status, data = self._git_request(\"GET\", url, params={\"recursive\": \"1\"})\n        if status != 200 or not data:\n            logger.warning(f\"[Gallery] 获取固定 GitHub tree 失败 (HTTP {status})\")\n            return None\n        if data.get(\"truncated\"):\n            logger.warning(\"[Gallery] 固定 GitHub tree 被截断，为避免误重编号，本次中止。\")\n            return None\n        result = []\n        for entry in data.get(\"tree\", []):\n            if entry.get(\"type\") == \"blob\":\n                result.append({\n                    \"path\": entry[\"path\"],\n                    \"sha\": entry.get(\"sha\", \"\"),\n                    \"size\": entry.get(\"size\", 0),\n                })\n        return result\n\n    def _ensure_perceptual_index(self) -> None:\n'''
assert old_tree_tail in source, "tree insertion anchor not found"
source = source.replace(old_tree_tail, new_tree_tail, 1)

old_commit = '''    def _github_commit_renumber(\n        self,\n        plan: tuple[RenameStep, ...],\n        tree: list[dict],\n        manifest_payload: bytes,\n    ) -> bool:\n        if self._git_platform() != \"github\":\n            return False\n        blobs = {\n            str(entry.get(\"path\", \"\")): str(entry.get(\"sha\", \"\"))\n            for entry in tree\n            if str(entry.get(\"sha\", \"\"))\n        }\n        final_targets = {step.target for step in plan}\n        source_paths = {step.source for step in plan}\n        entries: list[dict] = []\n        for step in plan:\n            blob_sha = blobs.get(step.source)\n            if not blob_sha:\n                logger.warning(f\"[Gallery] 远程重编号缺少 blob SHA：{step.source}\")\n                return False\n            entries.append({\"path\": step.target, \"mode\": \"100644\", \"type\": \"blob\", \"sha\": blob_sha})\n        for old_path in sorted(source_paths - final_targets):\n            entries.append({\"path\": old_path, \"mode\": \"100644\", \"type\": \"blob\", \"sha\": None})\n        manifest_sha = self._git_create_github_blob(manifest_payload)\n        if not manifest_sha:\n            return False\n        entries.append({\"path\": GALLERY_INDEX_PATH, \"mode\": \"100644\", \"type\": \"blob\", \"sha\": manifest_sha})\n\n        for attempt in range(2):\n            head = self._git_get_head_commit_and_tree()\n            if not head:\n                return False\n            parent_sha, base_tree_sha = head\n            tree_sha = self._git_create_github_tree(base_tree_sha, entries)\n            if not tree_sha:\n                return False\n            commit_sha = self._git_create_github_commit(\n                f\"Renumber {len(plan)} gallery images\",\n                tree_sha,\n                parent_sha,\n            )\n            if commit_sha and self._git_update_github_ref(commit_sha):\n                return True\n            if attempt == 0:\n                logger.info(\"[Gallery] 重编号 ref 冲突，刷新 HEAD 后重试一次。\")\n        return False\n'''
new_commit = '''    def _github_commit_renumber(\n        self,\n        plan: tuple[RenameStep, ...],\n        tree: list[dict],\n        manifest_payload: bytes,\n        *,\n        expected_head_sha: str,\n        base_tree_sha: str,\n    ) -> bool:\n        \"\"\"Commit one renumber plan only against the HEAD/tree it was planned from.\"\"\"\n        if self._git_platform() != \"github\":\n            return False\n        current_head = self._git_get_head_commit_and_tree()\n        if not current_head or current_head[0] != expected_head_sha:\n            logger.warning(\"[Gallery] 重编号期间 GitHub 已发生变化，拒绝基于新 HEAD 继续提交。\")\n            return False\n\n        blobs = {\n            str(entry.get(\"path\", \"\")): str(entry.get(\"sha\", \"\"))\n            for entry in tree\n            if str(entry.get(\"sha\", \"\"))\n        }\n        final_targets = {step.target for step in plan}\n        source_paths = {step.source for step in plan}\n        entries: list[dict] = []\n        for step in plan:\n            blob_sha = blobs.get(step.source)\n            if not blob_sha:\n                logger.warning(f\"[Gallery] 远程重编号缺少 blob SHA：{step.source}\")\n                return False\n            entries.append({\"path\": step.target, \"mode\": \"100644\", \"type\": \"blob\", \"sha\": blob_sha})\n        for old_path in sorted(source_paths - final_targets):\n            entries.append({\"path\": old_path, \"mode\": \"100644\", \"type\": \"blob\", \"sha\": None})\n        manifest_sha = self._git_create_github_blob(manifest_payload)\n        if not manifest_sha:\n            return False\n        entries.append({\"path\": GALLERY_INDEX_PATH, \"mode\": \"100644\", \"type\": \"blob\", \"sha\": manifest_sha})\n\n        tree_sha = self._git_create_github_tree(base_tree_sha, entries)\n        if not tree_sha:\n            return False\n        commit_sha = self._git_create_github_commit(\n            f\"Renumber {len(plan)} gallery images\",\n            tree_sha,\n            expected_head_sha,\n        )\n        if not commit_sha:\n            return False\n        if self._git_update_github_ref(commit_sha):\n            return True\n        logger.warning(\"[Gallery] GitHub HEAD 在重编号提交期间发生变化，非快进更新已被拒绝。\")\n        return False\n'''
assert old_commit in source, "renumber commit block not found"
source = source.replace(old_commit, new_commit, 1)

old_snapshot = '''        try:\n            tree = self._git_list_tree()\n            if tree is None:\n                return {\"ok\": False, \"error\": \"远程图库状态无法确认，本次未执行重编号。\"}\n            remote_paths = sorted(\n'''
new_snapshot = '''        try:\n            head = self._git_get_head_commit_and_tree()\n            if not head:\n                return {\"ok\": False, \"error\": \"远程图库状态无法确认，本次未执行重编号。\"}\n            expected_head_sha, base_tree_sha = head\n            tree = self._git_list_tree_at(base_tree_sha)\n            if tree is None:\n                return {\"ok\": False, \"error\": \"远程图库状态无法确认，本次未执行重编号。\"}\n            remote_paths = sorted(\n'''
assert old_snapshot in source, "renumber snapshot anchor not found"
source = source.replace(old_snapshot, new_snapshot, 1)

old_stage = '''            staged = self._stage_local_renumber(plan)\n            if not self._github_commit_renumber(plan, tree, manifest_payload):\n                self._rollback_local_renumber(staged)\n                return {\"ok\": False, \"error\": \"GitHub 重编号提交失败，本地临时改名已回滚。\"}\n'''
new_stage = '''            current_head = self._git_get_head_commit_and_tree()\n            if not current_head or current_head[0] != expected_head_sha:\n                return {\n                    \"ok\": False,\n                    \"error\": \"重编号期间 GitHub 已发生变化，本次没有改写任何本地编号，请重新执行 /导入图库。\",\n                }\n\n            staged = self._stage_local_renumber(plan)\n            if not self._github_commit_renumber(\n                plan,\n                tree,\n                manifest_payload,\n                expected_head_sha=expected_head_sha,\n                base_tree_sha=base_tree_sha,\n            ):\n                self._rollback_local_renumber(staged)\n                latest_head = self._git_get_head_commit_and_tree()\n                if latest_head and latest_head[0] != expected_head_sha:\n                    return {\n                        \"ok\": False,\n                        \"error\": \"重编号期间 GitHub 已发生变化，本地临时改名已回滚，请重新执行 /导入图库。\",\n                    }\n                return {\"ok\": False, \"error\": \"GitHub 重编号提交失败，本地临时改名已回滚。\"}\n'''
assert old_stage in source, "renumber stage block not found"
source = source.replace(old_stage, new_stage, 1)

path.write_text(source, encoding="utf-8")
