from pathlib import Path

path = Path("main.py")
source = path.read_text(encoding="utf-8")

old_api = '''        img_path_str = str(img_path)\n        img_path.unlink()\n        self._invalidate_category_hash_cache(category)\n        self._forget_file_hash(img_path)\n        # Git 远程删除\n        if self._git_sync_enabled:\n            asyncio.get_event_loop().run_in_executor(\n                None, self._git_delete_remote_file, img_path_str\n            )\n        return jsonify({"ok": True})\n'''
new_api = '''        if not await self._delete_image_consistently(img_path, category):\n            return jsonify({"ok": False, "error": "远程删除失败，本地文件已保留"}), 502\n        return jsonify({"ok": True})\n'''
assert old_api in source, "internal web delete block changed"
source = source.replace(old_api, new_api, 1)

old_remote = '''    def _git_delete_remote_file(self, local_abs_path: str) -> None:\n        """将本地文件的对应远程文件删除。"""\n        if not self._git_sync_enabled:\n            return\n        git_path = self._to_git_path(local_abs_path)\n        if not git_path:\n            return\n        try:\n            ok = self._git_delete_file(git_path, f"Delete {git_path}")\n            if ok:\n                logger.info(f"[Git Sync] 已从远程删除: {git_path}")\n        except Exception as exc:\n            logger.error(f"[Git Sync] 远程删除失败 {git_path}: {exc}")\n'''
new_remote = '''    def _git_delete_remote_file(self, local_abs_path: str) -> bool:\n        """删除本地路径对应的远程文件，并把结果反馈给一致性调用方。"""\n        if not self._git_sync_enabled:\n            return True\n        git_path = self._to_git_path(local_abs_path)\n        if not git_path:\n            return False\n        try:\n            ok = self._git_delete_file(git_path, f"Delete {git_path}")\n            if ok:\n                logger.info(f"[Git Sync] 已从远程删除: {git_path}")\n                return True\n            return False\n        except Exception as exc:\n            logger.error(f"[Git Sync] 远程删除失败 {git_path}: {exc}")\n            return False\n'''
assert old_remote in source, "remote delete helper changed"
source = source.replace(old_remote, new_remote, 1)

anchor = '''    def _rollback_stored_image(self, path: Path, category: str) -> None:\n        """Remove a local candidate when its required remote push did not complete."""\n        with self._gallery_write_lock:\n            try:\n                path.unlink(missing_ok=True)\n            except OSError as exc:\n                logger.warning(f"回滚上传文件失败 {path}: {exc}")\n            self._invalidate_category_hash_cache(category)\n            self._forget_file_hash(path)\n\n'''
helper = '''    async def _delete_image_consistently(self, image_path: Path, category: str) -> bool:\n        """远端启用时先确认远端删除成功，再提交本地删除。"""\n        if self._git_sync_enabled:\n            remote_ok = await asyncio.to_thread(\n                self._git_delete_remote_file, str(image_path)\n            )\n            if not remote_ok:\n                logger.warning(\n                    f"[Gallery] 远端删除失败，本地文件已保留: {image_path}"\n                )\n                return False\n\n        try:\n            image_path.unlink()\n        except FileNotFoundError:\n            return True\n        except OSError as exc:\n            logger.warning(f"[Gallery] 本地删除失败 {image_path}: {exc}")\n            return False\n\n        self._invalidate_category_hash_cache(category)\n        self._forget_file_hash(image_path)\n        return True\n\n'''
assert anchor in source, "rollback anchor changed"
source = source.replace(anchor, anchor + helper, 1)

old_handle = '''        for index in numbers:\n            image_path = self._find_by_index(index)\n            if not image_path:\n                missing_numbers.append(str(index))\n                continue\n            deleted_names.append(image_path.name)\n            image_path_str = str(image_path)\n            image_path.unlink()\n            self._invalidate_category_hash_cache(image_path.parent.name)\n            self._forget_file_hash(image_path)\n            # Git 远程删除（异步）\n            if self._git_sync_enabled:\n                asyncio.get_event_loop().run_in_executor(\n                    None, self._git_delete_remote_file, image_path_str\n                )\n\n        if deleted_names and missing_numbers:\n            message = (\n                f"已删除：{'、'.join(deleted_names)}\\n"\n                f"未找到：{'、'.join(missing_numbers)}"\n            )\n        elif deleted_names:\n            message = f"已删除：{'、'.join(deleted_names)}"\n        else:\n            message = f"未找到编号为 {'、'.join(missing_numbers)} 的图片或表情包。"\n'''
new_handle = '''        failed_names: list[str] = []\n        for index in numbers:\n            image_path = self._find_by_index(index)\n            if not image_path:\n                missing_numbers.append(str(index))\n                continue\n            if await self._delete_image_consistently(\n                image_path, image_path.parent.name\n            ):\n                deleted_names.append(image_path.name)\n            else:\n                failed_names.append(image_path.name)\n\n        message_parts: list[str] = []\n        if deleted_names:\n            message_parts.append(f"已删除：{'、'.join(deleted_names)}")\n        if missing_numbers:\n            message_parts.append(f"未找到：{'、'.join(missing_numbers)}")\n        if failed_names:\n            message_parts.append(\n                f"删除失败并已保留本地文件：{'、'.join(failed_names)}"\n            )\n        if message_parts:\n            message = "\\n".join(message_parts)\n        else:\n            message = "没有可删除的图片或表情包。"\n'''
assert old_handle in source, "chat delete block changed"
source = source.replace(old_handle, new_handle, 1)

old_dedupe = '''                if digest in seen_hashes:\n                    rel = image_path.relative_to(self.gallery_root).as_posix()\n                    git_path = self._to_git_path(str(image_path))\n                    image_path.unlink()\n                    self._invalidate_category_hash_cache(cat)\n                    self._forget_file_hash(image_path, save=False)\n                    if git_path:\n                        self._sha_cache.pop(git_path, None)\n                    if self._git_sync_enabled:\n                        asyncio.get_event_loop().run_in_executor(\n                            None, self._git_delete_remote_file, str(image_path)\n                        )\n                    removed += 1\n                    if len(deleted_examples) < 5:\n                        deleted_examples.append(rel)\n                    continue\n'''
new_dedupe = '''                if digest in seen_hashes:\n                    rel = image_path.relative_to(self.gallery_root).as_posix()\n                    git_path = self._to_git_path(str(image_path))\n                    if await self._delete_image_consistently(image_path, cat):\n                        if git_path:\n                            self._sha_cache.pop(git_path, None)\n                        removed += 1\n                        if len(deleted_examples) < 5:\n                            deleted_examples.append(rel)\n                    continue\n'''
assert old_dedupe in source, "dedupe delete block changed"
source = source.replace(old_dedupe, new_dedupe, 1)

path.write_text(source, encoding="utf-8")
