from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"expected block missing in {path}: {old[:120]!r}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


old_method = '''    def github_create_only_paths_exist_at_ref(\n        self, ref_sha: str, paths: set[str]\n    ) -> bool | None:\n        """Check only the paths being created at one immutable commit ref."""\n        if not paths:\n            return False\n        if self.platform() != "github" or not str(ref_sha).strip():\n            return None\n\n        def check_path(path: str) -> bool | None:\n            encoded = "/".join(quote(part, safe="") for part in str(path).split("/"))\n            url = (\n                f"{self.api_base()}/repos/{self.owner()}/{self.repo()}/contents/{encoded}"\n            )\n            status, _ = self.request(\n                "GET", url, params={"ref": str(ref_sha).strip()}, timeout=30\n            )\n            if status == 200:\n                return True\n            if status == 404:\n                return False\n            self._warning(\n                f"[Git Sync] 无法确认 GitHub create-only 路径占用状态 "\n                f"{path} (HTTP {status})。"\n            )\n            return None\n\n        ordered = sorted(paths)\n        max_workers = min(4, len(ordered))\n        with ThreadPoolExecutor(max_workers=max_workers) as executor:\n            results = list(executor.map(check_path, ordered))\n        if any(result is True for result in results):\n            return True\n        if any(result is None for result in results):\n            return None\n        return False\n'''
new_method = '''    def github_create_only_paths_exist_at_ref(\n        self, ref_sha: str, paths: set[str]\n    ) -> bool | None:\n        """Check create-only paths from bounded immutable directory snapshots."""\n        if not paths:\n            return False\n        if self.platform() != "github" or not str(ref_sha).strip():\n            return None\n\n        groups: dict[str, set[str]] = {}\n        for path in paths:\n            normalized = str(path).strip().strip("/")\n            if not normalized or "/" not in normalized:\n                return None\n            parent, _ = normalized.rsplit("/", 1)\n            groups.setdefault(parent, set()).add(normalized)\n\n        def check_directory(item: tuple[str, set[str]]) -> bool | None:\n            parent, wanted = item\n            encoded = "/".join(quote(part, safe="") for part in parent.split("/"))\n            url = (\n                f"{self.api_base()}/repos/{self.owner()}/{self.repo()}/contents/{encoded}"\n            )\n            status, data = self.request(\n                "GET", url, params={"ref": str(ref_sha).strip()}, timeout=30\n            )\n            if status == 404:\n                return False\n            if status != 200 or not isinstance(data, list):\n                self._warning(\n                    f"[Git Sync] 无法确认 GitHub create-only 目录占用状态 "\n                    f"{parent} (HTTP {status})。"\n                )\n                return None\n            existing = {\n                str(entry.get("path", "")).strip()\n                for entry in data\n                if isinstance(entry, Mapping)\n                and str(entry.get("type", "")).strip() == "file"\n                and str(entry.get("path", "")).strip()\n            }\n            return bool(existing.intersection(wanted))\n\n        ordered_groups = sorted(groups.items())\n        max_workers = min(4, len(ordered_groups))\n        with ThreadPoolExecutor(max_workers=max_workers) as executor:\n            results = list(executor.map(check_directory, ordered_groups))\n        if any(result is True for result in results):\n            return True\n        if any(result is None for result in results):\n            return None\n        return False\n'''
replace_once("gallery_remote.py", old_method, new_method)

old_test = '''    def request(method, url, json_body=None, params=None, **kwargs):\n        calls.append((method, url, params))\n        assert "/contents/gallery/airi/43.png" in url\n        assert params == {"ref": "commit-sha"}\n        return 404, None\n'''
new_test = '''    def request(method, url, json_body=None, params=None, **kwargs):\n        calls.append((method, url, params))\n        assert url.endswith("/contents/gallery/airi")\n        assert params == {"ref": "commit-sha"}\n        return 200, [{"type": "file", "path": "gallery/airi/42.png"}]\n'''
replace_once("tests/test_upload_hot_path_performance.py", old_test, new_test)

print("batched create-only GREEN patch applied")
